model:
  type: SpatialTransformerNetwork
  params:
    num_network: 4
    input_channels: 1
    hidden_layers: [16, 32, 64, 128, 256]
    kernel_size: [3, 3, 3, 3, 3]
    stride: [0, 2, 0, 2, 0]
    padding: [1, 1, 1, 1, 1]
    fc_hidden_size: 32
    fc_output_size: 8
